// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.sts.rpclib;

/**
 * Protobuf enum {@code com.sts.rpclib.AttendanceConditions}
 */
public enum AttendanceConditions
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_ATTENDANCE = 0;</code>
   */
  UNKNOWN_ATTENDANCE(0),
  /**
   * <code>SMALL = 1;</code>
   */
  SMALL(1),
  /**
   * <code>MEDIUM = 2;</code>
   */
  MEDIUM(2),
  /**
   * <code>FULL = 3;</code>
   */
  FULL(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_ATTENDANCE = 0;</code>
   */
  public static final int UNKNOWN_ATTENDANCE_VALUE = 0;
  /**
   * <code>SMALL = 1;</code>
   */
  public static final int SMALL_VALUE = 1;
  /**
   * <code>MEDIUM = 2;</code>
   */
  public static final int MEDIUM_VALUE = 2;
  /**
   * <code>FULL = 3;</code>
   */
  public static final int FULL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AttendanceConditions valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AttendanceConditions forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_ATTENDANCE;
      case 1: return SMALL;
      case 2: return MEDIUM;
      case 3: return FULL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AttendanceConditions>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AttendanceConditions> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AttendanceConditions>() {
          public AttendanceConditions findValueByNumber(int number) {
            return AttendanceConditions.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.sts.rpclib.Enums.getDescriptor().getEnumTypes().get(8);
  }

  private static final AttendanceConditions[] VALUES = values();

  public static AttendanceConditions valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AttendanceConditions(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.sts.rpclib.AttendanceConditions)
}

