// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package com.sts.rpclib;

public interface Base64ImageMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.Base64ImageMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string image_id = 1;</code>
   * @return The imageId.
   */
  java.lang.String getImageId();
  /**
   * <code>string image_id = 1;</code>
   * @return The bytes for imageId.
   */
  com.google.protobuf.ByteString
      getImageIdBytes();

  /**
   * <code>.com.sts.rpclib.ImageContentType content_type = 2;</code>
   * @return The enum numeric value on the wire for contentType.
   */
  int getContentTypeValue();
  /**
   * <code>.com.sts.rpclib.ImageContentType content_type = 2;</code>
   * @return The contentType.
   */
  com.sts.rpclib.ImageContentType getContentType();

  /**
   * <pre>
   * base64
   * </pre>
   *
   * <code>string value = 3;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * base64
   * </pre>
   *
   * <code>string value = 3;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.com.sts.rpclib.ImageType image_type = 5;</code>
   * @return The enum numeric value on the wire for imageType.
   */
  int getImageTypeValue();
  /**
   * <code>.com.sts.rpclib.ImageType image_type = 5;</code>
   * @return The imageType.
   */
  com.sts.rpclib.ImageType getImageType();
}
