// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookmakers.proto

package com.sts.rpclib;

public final class Bookmakers {
  private Bookmakers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020bookmakers.proto\022\016com.sts.rpclib*k\n\tBo" +
      "okmaker\022\025\n\021UNKNOWN_BOOKMAKER\020\000\022\024\n\020BETWAY" +
      "_BOOKMAKER\020\001\022\024\n\020BET365_BOOKMAKER\020\002\022\033\n\027BE" +
      "TWAY_AFRICA_BOOKMAKER\020\003B/P\001Z+github.com/" +
      "frontend210/protobuf/gorpclibb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
