// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: categories.proto

package com.sts.rpclib;

public interface CategoryMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.CategoryMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string season = 2;</code>
   * @return The season.
   */
  java.lang.String getSeason();
  /**
   * <code>string season = 2;</code>
   * @return The bytes for season.
   */
  com.google.protobuf.ByteString
      getSeasonBytes();

  /**
   * <code>.com.sts.rpclib.Sport sport = 3;</code>
   * @return The enum numeric value on the wire for sport.
   */
  int getSportValue();
  /**
   * <code>.com.sts.rpclib.Sport sport = 3;</code>
   * @return The sport.
   */
  com.sts.rpclib.Sport getSport();

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  com.sts.rpclib.LocalizedName getName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  int getNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getNameOrBuilder(
      int index);

  /**
   * <pre>
   *    repeated MatchStageMessage stage = 6;
   * </pre>
   *
   * <code>int64 updated = 5;</code>
   * @return The updated.
   */
  long getUpdated();
}
