// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: draw.proto

package com.sts.rpclib;

/**
 * Protobuf enum {@code com.sts.rpclib.DrawType}
 */
public enum DrawType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MALE_SINGLE_DRAW = 0;</code>
   */
  MALE_SINGLE_DRAW(0),
  /**
   * <code>MALE_DOUBLE_DRAW = 1;</code>
   */
  MALE_DOUBLE_DRAW(1),
  /**
   * <code>FEMALE_SINGLE_DRAW = 2;</code>
   */
  FEMALE_SINGLE_DRAW(2),
  /**
   * <code>FEMALE_DOUBLE_DRAW = 3;</code>
   */
  FEMALE_DOUBLE_DRAW(3),
  /**
   * <code>MIXED_DOUBLE_DRAW = 4;</code>
   */
  MIXED_DOUBLE_DRAW(4),
  /**
   * <code>TEAM_DRAW = 5;</code>
   */
  TEAM_DRAW(5),
  /**
   * <code>MALE_TEAM_DRAW = 6;</code>
   */
  MALE_TEAM_DRAW(6),
  /**
   * <code>FEMALE_TEAM_DRAW = 7;</code>
   */
  FEMALE_TEAM_DRAW(7),
  /**
   * <code>QUALIFICATION_DRAW = 8;</code>
   */
  QUALIFICATION_DRAW(8),
  /**
   * <code>MAIN_DRAW = 9;</code>
   */
  MAIN_DRAW(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MALE_SINGLE_DRAW = 0;</code>
   */
  public static final int MALE_SINGLE_DRAW_VALUE = 0;
  /**
   * <code>MALE_DOUBLE_DRAW = 1;</code>
   */
  public static final int MALE_DOUBLE_DRAW_VALUE = 1;
  /**
   * <code>FEMALE_SINGLE_DRAW = 2;</code>
   */
  public static final int FEMALE_SINGLE_DRAW_VALUE = 2;
  /**
   * <code>FEMALE_DOUBLE_DRAW = 3;</code>
   */
  public static final int FEMALE_DOUBLE_DRAW_VALUE = 3;
  /**
   * <code>MIXED_DOUBLE_DRAW = 4;</code>
   */
  public static final int MIXED_DOUBLE_DRAW_VALUE = 4;
  /**
   * <code>TEAM_DRAW = 5;</code>
   */
  public static final int TEAM_DRAW_VALUE = 5;
  /**
   * <code>MALE_TEAM_DRAW = 6;</code>
   */
  public static final int MALE_TEAM_DRAW_VALUE = 6;
  /**
   * <code>FEMALE_TEAM_DRAW = 7;</code>
   */
  public static final int FEMALE_TEAM_DRAW_VALUE = 7;
  /**
   * <code>QUALIFICATION_DRAW = 8;</code>
   */
  public static final int QUALIFICATION_DRAW_VALUE = 8;
  /**
   * <code>MAIN_DRAW = 9;</code>
   */
  public static final int MAIN_DRAW_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DrawType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DrawType forNumber(int value) {
    switch (value) {
      case 0: return MALE_SINGLE_DRAW;
      case 1: return MALE_DOUBLE_DRAW;
      case 2: return FEMALE_SINGLE_DRAW;
      case 3: return FEMALE_DOUBLE_DRAW;
      case 4: return MIXED_DOUBLE_DRAW;
      case 5: return TEAM_DRAW;
      case 6: return MALE_TEAM_DRAW;
      case 7: return FEMALE_TEAM_DRAW;
      case 8: return QUALIFICATION_DRAW;
      case 9: return MAIN_DRAW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DrawType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DrawType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DrawType>() {
          public DrawType findValueByNumber(int number) {
            return DrawType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.sts.rpclib.Draw.getDescriptor().getEnumTypes().get(0);
  }

  private static final DrawType[] VALUES = values();

  public static DrawType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DrawType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.sts.rpclib.DrawType)
}

