// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: h2h.proto

package com.sts.rpclib;

/**
 * Protobuf type {@code com.sts.rpclib.H2HParticipantMessage}
 */
public final class H2HParticipantMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sts.rpclib.H2HParticipantMessage)
    H2HParticipantMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use H2HParticipantMessage.newBuilder() to construct.
  private H2HParticipantMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private H2HParticipantMessage() {
    position_ = 0;
    participantId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new H2HParticipantMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sts.rpclib.H2H.internal_static_com_sts_rpclib_H2HParticipantMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sts.rpclib.H2H.internal_static_com_sts_rpclib_H2HParticipantMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sts.rpclib.H2HParticipantMessage.class, com.sts.rpclib.H2HParticipantMessage.Builder.class);
  }

  public static final int POSITION_FIELD_NUMBER = 1;
  private int position_ = 0;
  /**
   * <code>.com.sts.rpclib.Teams position = 1;</code>
   * @return The enum numeric value on the wire for position.
   */
  @java.lang.Override public int getPositionValue() {
    return position_;
  }
  /**
   * <code>.com.sts.rpclib.Teams position = 1;</code>
   * @return The position.
   */
  @java.lang.Override public com.sts.rpclib.Teams getPosition() {
    com.sts.rpclib.Teams result = com.sts.rpclib.Teams.forNumber(position_);
    return result == null ? com.sts.rpclib.Teams.UNRECOGNIZED : result;
  }

  public static final int PARTICIPANTID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object participantId_ = "";
  /**
   * <code>string participantId = 2;</code>
   * @return The participantId.
   */
  @java.lang.Override
  public java.lang.String getParticipantId() {
    java.lang.Object ref = participantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      participantId_ = s;
      return s;
    }
  }
  /**
   * <code>string participantId = 2;</code>
   * @return The bytes for participantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParticipantIdBytes() {
    java.lang.Object ref = participantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      participantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTICIPANTNAME_FIELD_NUMBER = 3;
  private com.sts.rpclib.LocalizedName participantName_;
  /**
   * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
   * @return Whether the participantName field is set.
   */
  @java.lang.Override
  public boolean hasParticipantName() {
    return participantName_ != null;
  }
  /**
   * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
   * @return The participantName.
   */
  @java.lang.Override
  public com.sts.rpclib.LocalizedName getParticipantName() {
    return participantName_ == null ? com.sts.rpclib.LocalizedName.getDefaultInstance() : participantName_;
  }
  /**
   * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
   */
  @java.lang.Override
  public com.sts.rpclib.LocalizedNameOrBuilder getParticipantNameOrBuilder() {
    return participantName_ == null ? com.sts.rpclib.LocalizedName.getDefaultInstance() : participantName_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (position_ != com.sts.rpclib.Teams.home.getNumber()) {
      output.writeEnum(1, position_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(participantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, participantId_);
    }
    if (participantName_ != null) {
      output.writeMessage(3, getParticipantName());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (position_ != com.sts.rpclib.Teams.home.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, position_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(participantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, participantId_);
    }
    if (participantName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getParticipantName());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sts.rpclib.H2HParticipantMessage)) {
      return super.equals(obj);
    }
    com.sts.rpclib.H2HParticipantMessage other = (com.sts.rpclib.H2HParticipantMessage) obj;

    if (position_ != other.position_) return false;
    if (!getParticipantId()
        .equals(other.getParticipantId())) return false;
    if (hasParticipantName() != other.hasParticipantName()) return false;
    if (hasParticipantName()) {
      if (!getParticipantName()
          .equals(other.getParticipantName())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + position_;
    hash = (37 * hash) + PARTICIPANTID_FIELD_NUMBER;
    hash = (53 * hash) + getParticipantId().hashCode();
    if (hasParticipantName()) {
      hash = (37 * hash) + PARTICIPANTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getParticipantName().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sts.rpclib.H2HParticipantMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sts.rpclib.H2HParticipantMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sts.rpclib.H2HParticipantMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sts.rpclib.H2HParticipantMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.sts.rpclib.H2HParticipantMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sts.rpclib.H2HParticipantMessage)
      com.sts.rpclib.H2HParticipantMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sts.rpclib.H2H.internal_static_com_sts_rpclib_H2HParticipantMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sts.rpclib.H2H.internal_static_com_sts_rpclib_H2HParticipantMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sts.rpclib.H2HParticipantMessage.class, com.sts.rpclib.H2HParticipantMessage.Builder.class);
    }

    // Construct using com.sts.rpclib.H2HParticipantMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      position_ = 0;
      participantId_ = "";
      participantName_ = null;
      if (participantNameBuilder_ != null) {
        participantNameBuilder_.dispose();
        participantNameBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sts.rpclib.H2H.internal_static_com_sts_rpclib_H2HParticipantMessage_descriptor;
    }

    @java.lang.Override
    public com.sts.rpclib.H2HParticipantMessage getDefaultInstanceForType() {
      return com.sts.rpclib.H2HParticipantMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.sts.rpclib.H2HParticipantMessage build() {
      com.sts.rpclib.H2HParticipantMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sts.rpclib.H2HParticipantMessage buildPartial() {
      com.sts.rpclib.H2HParticipantMessage result = new com.sts.rpclib.H2HParticipantMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sts.rpclib.H2HParticipantMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.position_ = position_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.participantId_ = participantId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.participantName_ = participantNameBuilder_ == null
            ? participantName_
            : participantNameBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sts.rpclib.H2HParticipantMessage) {
        return mergeFrom((com.sts.rpclib.H2HParticipantMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sts.rpclib.H2HParticipantMessage other) {
      if (other == com.sts.rpclib.H2HParticipantMessage.getDefaultInstance()) return this;
      if (other.position_ != 0) {
        setPositionValue(other.getPositionValue());
      }
      if (!other.getParticipantId().isEmpty()) {
        participantId_ = other.participantId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasParticipantName()) {
        mergeParticipantName(other.getParticipantName());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              position_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              participantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getParticipantNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int position_ = 0;
    /**
     * <code>.com.sts.rpclib.Teams position = 1;</code>
     * @return The enum numeric value on the wire for position.
     */
    @java.lang.Override public int getPositionValue() {
      return position_;
    }
    /**
     * <code>.com.sts.rpclib.Teams position = 1;</code>
     * @param value The enum numeric value on the wire for position to set.
     * @return This builder for chaining.
     */
    public Builder setPositionValue(int value) {
      position_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.Teams position = 1;</code>
     * @return The position.
     */
    @java.lang.Override
    public com.sts.rpclib.Teams getPosition() {
      com.sts.rpclib.Teams result = com.sts.rpclib.Teams.forNumber(position_);
      return result == null ? com.sts.rpclib.Teams.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.sts.rpclib.Teams position = 1;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(com.sts.rpclib.Teams value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      position_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.Teams position = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000001);
      position_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object participantId_ = "";
    /**
     * <code>string participantId = 2;</code>
     * @return The participantId.
     */
    public java.lang.String getParticipantId() {
      java.lang.Object ref = participantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        participantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string participantId = 2;</code>
     * @return The bytes for participantId.
     */
    public com.google.protobuf.ByteString
        getParticipantIdBytes() {
      java.lang.Object ref = participantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        participantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string participantId = 2;</code>
     * @param value The participantId to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      participantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string participantId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipantId() {
      participantId_ = getDefaultInstance().getParticipantId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string participantId = 2;</code>
     * @param value The bytes for participantId to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      participantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.sts.rpclib.LocalizedName participantName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sts.rpclib.LocalizedName, com.sts.rpclib.LocalizedName.Builder, com.sts.rpclib.LocalizedNameOrBuilder> participantNameBuilder_;
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     * @return Whether the participantName field is set.
     */
    public boolean hasParticipantName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     * @return The participantName.
     */
    public com.sts.rpclib.LocalizedName getParticipantName() {
      if (participantNameBuilder_ == null) {
        return participantName_ == null ? com.sts.rpclib.LocalizedName.getDefaultInstance() : participantName_;
      } else {
        return participantNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    public Builder setParticipantName(com.sts.rpclib.LocalizedName value) {
      if (participantNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        participantName_ = value;
      } else {
        participantNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    public Builder setParticipantName(
        com.sts.rpclib.LocalizedName.Builder builderForValue) {
      if (participantNameBuilder_ == null) {
        participantName_ = builderForValue.build();
      } else {
        participantNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    public Builder mergeParticipantName(com.sts.rpclib.LocalizedName value) {
      if (participantNameBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          participantName_ != null &&
          participantName_ != com.sts.rpclib.LocalizedName.getDefaultInstance()) {
          getParticipantNameBuilder().mergeFrom(value);
        } else {
          participantName_ = value;
        }
      } else {
        participantNameBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    public Builder clearParticipantName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      participantName_ = null;
      if (participantNameBuilder_ != null) {
        participantNameBuilder_.dispose();
        participantNameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    public com.sts.rpclib.LocalizedName.Builder getParticipantNameBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getParticipantNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    public com.sts.rpclib.LocalizedNameOrBuilder getParticipantNameOrBuilder() {
      if (participantNameBuilder_ != null) {
        return participantNameBuilder_.getMessageOrBuilder();
      } else {
        return participantName_ == null ?
            com.sts.rpclib.LocalizedName.getDefaultInstance() : participantName_;
      }
    }
    /**
     * <code>.com.sts.rpclib.LocalizedName participantName = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sts.rpclib.LocalizedName, com.sts.rpclib.LocalizedName.Builder, com.sts.rpclib.LocalizedNameOrBuilder> 
        getParticipantNameFieldBuilder() {
      if (participantNameBuilder_ == null) {
        participantNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sts.rpclib.LocalizedName, com.sts.rpclib.LocalizedName.Builder, com.sts.rpclib.LocalizedNameOrBuilder>(
                getParticipantName(),
                getParentForChildren(),
                isClean());
        participantName_ = null;
      }
      return participantNameBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sts.rpclib.H2HParticipantMessage)
  }

  // @@protoc_insertion_point(class_scope:com.sts.rpclib.H2HParticipantMessage)
  private static final com.sts.rpclib.H2HParticipantMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sts.rpclib.H2HParticipantMessage();
  }

  public static com.sts.rpclib.H2HParticipantMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<H2HParticipantMessage>
      PARSER = new com.google.protobuf.AbstractParser<H2HParticipantMessage>() {
    @java.lang.Override
    public H2HParticipantMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<H2HParticipantMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<H2HParticipantMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sts.rpclib.H2HParticipantMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

