// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incident.proto

package com.sts.rpclib;

public interface IncidentMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.IncidentMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The type of incident the message is about
   * </pre>
   *
   * <code>.com.sts.rpclib.IncidentType incidentType = 2;</code>
   * @return The enum numeric value on the wire for incidentType.
   */
  int getIncidentTypeValue();
  /**
   * <pre>
   * The type of incident the message is about
   * </pre>
   *
   * <code>.com.sts.rpclib.IncidentType incidentType = 2;</code>
   * @return The incidentType.
   */
  com.sts.rpclib.IncidentType getIncidentType();

  /**
   * <code>.com.sts.rpclib.Period period = 3;</code>
   * @return The enum numeric value on the wire for period.
   */
  int getPeriodValue();
  /**
   * <code>.com.sts.rpclib.Period period = 3;</code>
   * @return The period.
   */
  com.sts.rpclib.Period getPeriod();

  /**
   * <pre>
   * the minute of the incident
   * </pre>
   *
   * <code>int32 minute = 4;</code>
   * @return The minute.
   */
  int getMinute();

  /**
   * <pre>
   * the second of the incident: in case for example of Ice Hockey
   * </pre>
   *
   * <code>int32 second = 5;</code>
   * @return The second.
   */
  int getSecond();

  /**
   * <pre>
   * this marks whether the incident is about the home or away team
   * </pre>
   *
   * <code>int32 teamNumber = 6;</code>
   * @return The teamNumber.
   */
  int getTeamNumber();

  /**
   * <pre>
   * Player id
   * </pre>
   *
   * <code>int64 playerId = 7;</code>
   * @return The playerId.
   */
  long getPlayerId();

  /**
   * <pre>
   * the playerIdOut, in case of substitution
   * </pre>
   *
   * <code>int64 playerIdOut = 8;</code>
   * @return The playerIdOut.
   */
  long getPlayerIdOut();

  /**
   * <pre>
   * Player T shirt number
   * </pre>
   *
   * <code>int32 playerNum = 9;</code>
   * @return The playerNum.
   */
  int getPlayerNum();

  /**
   * <pre>
   * Player T shirt number in case of subs
   * </pre>
   *
   * <code>int32 playerNumOut = 10;</code>
   * @return The playerNumOut.
   */
  int getPlayerNumOut();

  /**
   * <pre>
   * Player name
   * </pre>
   *
   * <code>string playerName = 11;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <pre>
   * Player name
   * </pre>
   *
   * <code>string playerName = 11;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <code>string playerNameOut = 12;</code>
   * @return The playerNameOut.
   */
  java.lang.String getPlayerNameOut();
  /**
   * <code>string playerNameOut = 12;</code>
   * @return The bytes for playerNameOut.
   */
  com.google.protobuf.ByteString
      getPlayerNameOutBytes();

  /**
   * <pre>
   * Player short name: can be for example the Shirt Name
   * </pre>
   *
   * <code>string playerShortName = 13;</code>
   * @return The playerShortName.
   */
  java.lang.String getPlayerShortName();
  /**
   * <pre>
   * Player short name: can be for example the Shirt Name
   * </pre>
   *
   * <code>string playerShortName = 13;</code>
   * @return The bytes for playerShortName.
   */
  com.google.protobuf.ByteString
      getPlayerShortNameBytes();

  /**
   * <code>string playerShortNameOut = 14;</code>
   * @return The playerShortNameOut.
   */
  java.lang.String getPlayerShortNameOut();
  /**
   * <code>string playerShortNameOut = 14;</code>
   * @return The bytes for playerShortNameOut.
   */
  com.google.protobuf.ByteString
      getPlayerShortNameOutBytes();

  /**
   * <code>repeated int32 score = 15 [packed = true];</code>
   * @return A list containing the score.
   */
  java.util.List<java.lang.Integer> getScoreList();
  /**
   * <code>repeated int32 score = 15 [packed = true];</code>
   * @return The count of score.
   */
  int getScoreCount();
  /**
   * <code>repeated int32 score = 15 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The score at the given index.
   */
  int getScore(int index);

  /**
   * <pre>
   * Additional information about the incident (goal via header for example)
   * </pre>
   *
   * <code>string extraInfo = 16;</code>
   * @return The extraInfo.
   */
  java.lang.String getExtraInfo();
  /**
   * <pre>
   * Additional information about the incident (goal via header for example)
   * </pre>
   *
   * <code>string extraInfo = 16;</code>
   * @return The bytes for extraInfo.
   */
  com.google.protobuf.ByteString
      getExtraInfoBytes();

  /**
   * <code>bool isShootoutWithTotalScore = 17;</code>
   * @return The isShootoutWithTotalScore.
   */
  boolean getIsShootoutWithTotalScore();

  /**
   * <code>.com.sts.rpclib.UpdateAction action = 18;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.com.sts.rpclib.UpdateAction action = 18;</code>
   * @return The action.
   */
  com.sts.rpclib.UpdateAction getAction();

  /**
   * <code>bool isPlayerDataConfirmed = 19;</code>
   * @return The isPlayerDataConfirmed.
   */
  boolean getIsPlayerDataConfirmed();

  /**
   * <code>int32 sort_order = 20;</code>
   * @return The sortOrder.
   */
  int getSortOrder();

  /**
   * <code>string refIncidentId = 21;</code>
   * @return The refIncidentId.
   */
  java.lang.String getRefIncidentId();
  /**
   * <code>string refIncidentId = 21;</code>
   * @return The bytes for refIncidentId.
   */
  com.google.protobuf.ByteString
      getRefIncidentIdBytes();

  /**
   * <code>repeated .com.sts.rpclib.AssistMessage assists = 22;</code>
   */
  java.util.List<com.sts.rpclib.AssistMessage> 
      getAssistsList();
  /**
   * <code>repeated .com.sts.rpclib.AssistMessage assists = 22;</code>
   */
  com.sts.rpclib.AssistMessage getAssists(int index);
  /**
   * <code>repeated .com.sts.rpclib.AssistMessage assists = 22;</code>
   */
  int getAssistsCount();
  /**
   * <code>repeated .com.sts.rpclib.AssistMessage assists = 22;</code>
   */
  java.util.List<? extends com.sts.rpclib.AssistMessageOrBuilder> 
      getAssistsOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.AssistMessage assists = 22;</code>
   */
  com.sts.rpclib.AssistMessageOrBuilder getAssistsOrBuilder(
      int index);

  /**
   * <code>int64 timestamp = 23;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int32 minutePlus = 24;</code>
   * @return The minutePlus.
   */
  int getMinutePlus();
}
