// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: league_tables.proto

package com.sts.rpclib;

public interface LeagueTableMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.LeagueTableMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string categoryId = 1;</code>
   * @return The categoryId.
   */
  java.lang.String getCategoryId();
  /**
   * <code>string categoryId = 1;</code>
   * @return The bytes for categoryId.
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName categoryName = 2;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getCategoryNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName categoryName = 2;</code>
   */
  com.sts.rpclib.LocalizedName getCategoryName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName categoryName = 2;</code>
   */
  int getCategoryNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName categoryName = 2;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getCategoryNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName categoryName = 2;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getCategoryNameOrBuilder(
      int index);

  /**
   * <code>string stageId = 3;</code>
   * @return The stageId.
   */
  java.lang.String getStageId();
  /**
   * <code>string stageId = 3;</code>
   * @return The bytes for stageId.
   */
  com.google.protobuf.ByteString
      getStageIdBytes();

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName stageName = 4;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getStageNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName stageName = 4;</code>
   */
  com.sts.rpclib.LocalizedName getStageName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName stageName = 4;</code>
   */
  int getStageNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName stageName = 4;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getStageNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName stageName = 4;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getStageNameOrBuilder(
      int index);

  /**
   * <code>repeated .com.sts.rpclib.LeagueTableEntry entries = 5;</code>
   */
  java.util.List<com.sts.rpclib.LeagueTableEntry> 
      getEntriesList();
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableEntry entries = 5;</code>
   */
  com.sts.rpclib.LeagueTableEntry getEntries(int index);
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableEntry entries = 5;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableEntry entries = 5;</code>
   */
  java.util.List<? extends com.sts.rpclib.LeagueTableEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableEntry entries = 5;</code>
   */
  com.sts.rpclib.LeagueTableEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>.com.sts.rpclib.LeagueTableMessage.LeagueTableGroups leagueTableGroups = 6;</code>
   * @return The enum numeric value on the wire for leagueTableGroups.
   */
  int getLeagueTableGroupsValue();
  /**
   * <code>.com.sts.rpclib.LeagueTableMessage.LeagueTableGroups leagueTableGroups = 6;</code>
   * @return The leagueTableGroups.
   */
  com.sts.rpclib.LeagueTableMessage.LeagueTableGroups getLeagueTableGroups();

  /**
   * <code>.com.sts.rpclib.Sport sport = 7;</code>
   * @return The enum numeric value on the wire for sport.
   */
  int getSportValue();
  /**
   * <code>.com.sts.rpclib.Sport sport = 7;</code>
   * @return The sport.
   */
  com.sts.rpclib.Sport getSport();

  /**
   * <code>string season = 8;</code>
   * @return The season.
   */
  java.lang.String getSeason();
  /**
   * <code>string season = 8;</code>
   * @return The bytes for season.
   */
  com.google.protobuf.ByteString
      getSeasonBytes();

  /**
   * <code>string name = 9;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 9;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .com.sts.rpclib.LeagueTableAdditionalInfo additionalInfo = 10;</code>
   */
  java.util.List<com.sts.rpclib.LeagueTableAdditionalInfo> 
      getAdditionalInfoList();
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableAdditionalInfo additionalInfo = 10;</code>
   */
  com.sts.rpclib.LeagueTableAdditionalInfo getAdditionalInfo(int index);
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableAdditionalInfo additionalInfo = 10;</code>
   */
  int getAdditionalInfoCount();
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableAdditionalInfo additionalInfo = 10;</code>
   */
  java.util.List<? extends com.sts.rpclib.LeagueTableAdditionalInfoOrBuilder> 
      getAdditionalInfoOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LeagueTableAdditionalInfo additionalInfo = 10;</code>
   */
  com.sts.rpclib.LeagueTableAdditionalInfoOrBuilder getAdditionalInfoOrBuilder(
      int index);

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName tableName = 11;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getTableNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName tableName = 11;</code>
   */
  com.sts.rpclib.LocalizedName getTableName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName tableName = 11;</code>
   */
  int getTableNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName tableName = 11;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getTableNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName tableName = 11;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getTableNameOrBuilder(
      int index);
}
