// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match.proto

package com.sts.rpclib;

public interface MatchStatusChangeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.MatchStatusChangeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.sts.rpclib.MatchStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.sts.rpclib.MatchStatus status = 1;</code>
   * @return The status.
   */
  com.sts.rpclib.MatchStatus getStatus();

  /**
   * <code>.com.sts.rpclib.MatchOverallStatus overall = 2;</code>
   * @return The enum numeric value on the wire for overall.
   */
  int getOverallValue();
  /**
   * <code>.com.sts.rpclib.MatchOverallStatus overall = 2;</code>
   * @return The overall.
   */
  com.sts.rpclib.MatchOverallStatus getOverall();

  /**
   * <code>int64 startTime = 3;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 providedEndTime = 4;</code>
   * @return The providedEndTime.
   */
  long getProvidedEndTime();

  /**
   * <code>int64 scheduledEndTime = 5;</code>
   * @return The scheduledEndTime.
   */
  long getScheduledEndTime();

  /**
   * <code>map&lt;int32, int32&gt; injuryTime = 6;</code>
   */
  int getInjuryTimeCount();
  /**
   * <code>map&lt;int32, int32&gt; injuryTime = 6;</code>
   */
  boolean containsInjuryTime(
      int key);
  /**
   * Use {@link #getInjuryTimeMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getInjuryTime();
  /**
   * <code>map&lt;int32, int32&gt; injuryTime = 6;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getInjuryTimeMap();
  /**
   * <code>map&lt;int32, int32&gt; injuryTime = 6;</code>
   */
  int getInjuryTimeOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; injuryTime = 6;</code>
   */
  int getInjuryTimeOrThrow(
      int key);

  /**
   * <pre>
   * some providers offer the current second
   * </pre>
   *
   * <code>int32 playTime = 7;</code>
   * @return The playTime.
   */
  int getPlayTime();

  /**
   * <code>int32 elapsed = 8;</code>
   * @return The elapsed.
   */
  int getElapsed();

  /**
   * <code>int32 elapsedInjuryTime = 9;</code>
   * @return The elapsedInjuryTime.
   */
  int getElapsedInjuryTime();

  /**
   * <code>.com.sts.rpclib.ElapsedType elapsedType = 10;</code>
   * @return The enum numeric value on the wire for elapsedType.
   */
  int getElapsedTypeValue();
  /**
   * <code>.com.sts.rpclib.ElapsedType elapsedType = 10;</code>
   * @return The elapsedType.
   */
  com.sts.rpclib.ElapsedType getElapsedType();

  /**
   * <code>string description = 11;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 11;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string description2 = 12;</code>
   * @return The description2.
   */
  java.lang.String getDescription2();
  /**
   * <code>string description2 = 12;</code>
   * @return The bytes for description2.
   */
  com.google.protobuf.ByteString
      getDescription2Bytes();
}
