// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.sts.rpclib;

/**
 * Protobuf enum {@code com.sts.rpclib.ParticipantKind}
 */
public enum ParticipantKind
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_KIND = 0;</code>
   */
  UNKNOWN_KIND(0),
  /**
   * <code>TEAM = 1;</code>
   */
  TEAM(1),
  /**
   * <code>ATHLETE = 2;</code>
   */
  ATHLETE(2),
  /**
   * <code>ORGANISATION = 3;</code>
   */
  ORGANISATION(3),
  /**
   * <code>COACH_KIND = 4;</code>
   */
  COACH_KIND(4),
  /**
   * <code>REFEREE = 5;</code>
   */
  REFEREE(5),
  /**
   * <code>REFEREE_ASSISTANT = 6;</code>
   */
  REFEREE_ASSISTANT(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_KIND = 0;</code>
   */
  public static final int UNKNOWN_KIND_VALUE = 0;
  /**
   * <code>TEAM = 1;</code>
   */
  public static final int TEAM_VALUE = 1;
  /**
   * <code>ATHLETE = 2;</code>
   */
  public static final int ATHLETE_VALUE = 2;
  /**
   * <code>ORGANISATION = 3;</code>
   */
  public static final int ORGANISATION_VALUE = 3;
  /**
   * <code>COACH_KIND = 4;</code>
   */
  public static final int COACH_KIND_VALUE = 4;
  /**
   * <code>REFEREE = 5;</code>
   */
  public static final int REFEREE_VALUE = 5;
  /**
   * <code>REFEREE_ASSISTANT = 6;</code>
   */
  public static final int REFEREE_ASSISTANT_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ParticipantKind valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ParticipantKind forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_KIND;
      case 1: return TEAM;
      case 2: return ATHLETE;
      case 3: return ORGANISATION;
      case 4: return COACH_KIND;
      case 5: return REFEREE;
      case 6: return REFEREE_ASSISTANT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ParticipantKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ParticipantKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ParticipantKind>() {
          public ParticipantKind findValueByNumber(int number) {
            return ParticipantKind.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.sts.rpclib.Enums.getDescriptor().getEnumTypes().get(21);
  }

  private static final ParticipantKind[] VALUES = values();

  public static ParticipantKind valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ParticipantKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.sts.rpclib.ParticipantKind)
}

