// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match.proto

package com.sts.rpclib;

public interface ParticipantMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.ParticipantMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 1;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 1;</code>
   */
  com.sts.rpclib.LocalizedName getName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 1;</code>
   */
  int getNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 1;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 1;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getNameOrBuilder(
      int index);

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.com.sts.rpclib.ParticipantKind kn = 3;</code>
   * @return The enum numeric value on the wire for kn.
   */
  int getKnValue();
  /**
   * <code>.com.sts.rpclib.ParticipantKind kn = 3;</code>
   * @return The kn.
   */
  com.sts.rpclib.ParticipantKind getKn();

  /**
   * <code>.com.sts.rpclib.CountryMessage country = 4;</code>
   * @return Whether the country field is set.
   */
  boolean hasCountry();
  /**
   * <code>.com.sts.rpclib.CountryMessage country = 4;</code>
   * @return The country.
   */
  com.sts.rpclib.CountryMessage getCountry();
  /**
   * <code>.com.sts.rpclib.CountryMessage country = 4;</code>
   */
  com.sts.rpclib.CountryMessageOrBuilder getCountryOrBuilder();

  /**
   * <code>int32 position = 5;</code>
   * @return The position.
   */
  int getPosition();

  /**
   * <code>int32 gender = 6;</code>
   * @return The gender.
   */
  int getGender();

  /**
   * <code>int32 index = 7;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>string shortName = 8;</code>
   * @return The shortName.
   */
  java.lang.String getShortName();
  /**
   * <code>string shortName = 8;</code>
   * @return The bytes for shortName.
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <code>.com.sts.rpclib.MatchParticipantStatsMessage stats = 9;</code>
   * @return Whether the stats field is set.
   */
  boolean hasStats();
  /**
   * <code>.com.sts.rpclib.MatchParticipantStatsMessage stats = 9;</code>
   * @return The stats.
   */
  com.sts.rpclib.MatchParticipantStatsMessage getStats();
  /**
   * <code>.com.sts.rpclib.MatchParticipantStatsMessage stats = 9;</code>
   */
  com.sts.rpclib.MatchParticipantStatsMessageOrBuilder getStatsOrBuilder();

  /**
   * <code>.com.sts.rpclib.MatchParticipantJerseyMessage jersey = 10;</code>
   * @return Whether the jersey field is set.
   */
  boolean hasJersey();
  /**
   * <code>.com.sts.rpclib.MatchParticipantJerseyMessage jersey = 10;</code>
   * @return The jersey.
   */
  com.sts.rpclib.MatchParticipantJerseyMessage getJersey();
  /**
   * <code>.com.sts.rpclib.MatchParticipantJerseyMessage jersey = 10;</code>
   */
  com.sts.rpclib.MatchParticipantJerseyMessageOrBuilder getJerseyOrBuilder();

  /**
   * <code>string conferenceId = 11;</code>
   * @return The conferenceId.
   */
  java.lang.String getConferenceId();
  /**
   * <code>string conferenceId = 11;</code>
   * @return The bytes for conferenceId.
   */
  com.google.protobuf.ByteString
      getConferenceIdBytes();

  /**
   * <code>string conferenceName = 12;</code>
   * @return The conferenceName.
   */
  java.lang.String getConferenceName();
  /**
   * <code>string conferenceName = 12;</code>
   * @return The bytes for conferenceName.
   */
  com.google.protobuf.ByteString
      getConferenceNameBytes();

  /**
   * <code>string divisionId = 13;</code>
   * @return The divisionId.
   */
  java.lang.String getDivisionId();
  /**
   * <code>string divisionId = 13;</code>
   * @return The bytes for divisionId.
   */
  com.google.protobuf.ByteString
      getDivisionIdBytes();

  /**
   * <code>string divisionName = 14;</code>
   * @return The divisionName.
   */
  java.lang.String getDivisionName();
  /**
   * <code>string divisionName = 14;</code>
   * @return The bytes for divisionName.
   */
  com.google.protobuf.ByteString
      getDivisionNameBytes();

  /**
   * <code>string firstName = 15;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 15;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 16;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 16;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
