// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_profile.proto

package com.sts.rpclib;

public interface PlayerTeamMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.PlayerTeamMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 dateFrom = 1;</code>
   * @return The dateFrom.
   */
  long getDateFrom();

  /**
   * <code>int64 dateTo = 2;</code>
   * @return The dateTo.
   */
  long getDateTo();

  /**
   * <code>bool active = 3;</code>
   * @return The active.
   */
  boolean getActive();

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  com.sts.rpclib.LocalizedName getName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  int getNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 4;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getNameOrBuilder(
      int index);
}
