// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_profile.proto

package com.sts.rpclib;

/**
 * Protobuf type {@code com.sts.rpclib.PlayerMessage}
 */
public final class PlayerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sts.rpclib.PlayerMessage)
    PlayerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayerMessage.newBuilder() to construct.
  private PlayerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerMessage() {
    id_ = "";
    name_ = java.util.Collections.emptyList();
    position_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayerMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sts.rpclib.PlayerProfile.internal_static_com_sts_rpclib_PlayerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sts.rpclib.PlayerProfile.internal_static_com_sts_rpclib_PlayerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sts.rpclib.PlayerMessage.class, com.sts.rpclib.PlayerMessage.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.sts.rpclib.LocalizedName> name_;
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.sts.rpclib.LocalizedName> getNameList() {
    return name_;
  }
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getNameOrBuilderList() {
    return name_;
  }
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
   */
  @java.lang.Override
  public int getNameCount() {
    return name_.size();
  }
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
   */
  @java.lang.Override
  public com.sts.rpclib.LocalizedName getName(int index) {
    return name_.get(index);
  }
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
   */
  @java.lang.Override
  public com.sts.rpclib.LocalizedNameOrBuilder getNameOrBuilder(
      int index) {
    return name_.get(index);
  }

  public static final int DATEOFBIRTH_FIELD_NUMBER = 3;
  private long dateOfBirth_ = 0L;
  /**
   * <code>int64 dateOfBirth = 3;</code>
   * @return The dateOfBirth.
   */
  @java.lang.Override
  public long getDateOfBirth() {
    return dateOfBirth_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private double height_ = 0D;
  /**
   * <code>double height = 4;</code>
   * @return The height.
   */
  @java.lang.Override
  public double getHeight() {
    return height_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 5;
  private double weight_ = 0D;
  /**
   * <code>double weight = 5;</code>
   * @return The weight.
   */
  @java.lang.Override
  public double getWeight() {
    return weight_;
  }

  public static final int POSITION_FIELD_NUMBER = 6;
  private int position_ = 0;
  /**
   * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
   * @return The enum numeric value on the wire for position.
   */
  @java.lang.Override public int getPositionValue() {
    return position_;
  }
  /**
   * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
   * @return The position.
   */
  @java.lang.Override public com.sts.rpclib.ParticipantPosition getPosition() {
    com.sts.rpclib.ParticipantPosition result = com.sts.rpclib.ParticipantPosition.forNumber(position_);
    return result == null ? com.sts.rpclib.ParticipantPosition.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < name_.size(); i++) {
      output.writeMessage(2, name_.get(i));
    }
    if (dateOfBirth_ != 0L) {
      output.writeInt64(3, dateOfBirth_);
    }
    if (java.lang.Double.doubleToRawLongBits(height_) != 0) {
      output.writeDouble(4, height_);
    }
    if (java.lang.Double.doubleToRawLongBits(weight_) != 0) {
      output.writeDouble(5, weight_);
    }
    if (position_ != com.sts.rpclib.ParticipantPosition.UNKNOWN_PERSON_TYPE.getNumber()) {
      output.writeEnum(6, position_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < name_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, name_.get(i));
    }
    if (dateOfBirth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, dateOfBirth_);
    }
    if (java.lang.Double.doubleToRawLongBits(height_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, height_);
    }
    if (java.lang.Double.doubleToRawLongBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, weight_);
    }
    if (position_ != com.sts.rpclib.ParticipantPosition.UNKNOWN_PERSON_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, position_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sts.rpclib.PlayerMessage)) {
      return super.equals(obj);
    }
    com.sts.rpclib.PlayerMessage other = (com.sts.rpclib.PlayerMessage) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getNameList()
        .equals(other.getNameList())) return false;
    if (getDateOfBirth()
        != other.getDateOfBirth()) return false;
    if (java.lang.Double.doubleToLongBits(getHeight())
        != java.lang.Double.doubleToLongBits(
            other.getHeight())) return false;
    if (java.lang.Double.doubleToLongBits(getWeight())
        != java.lang.Double.doubleToLongBits(
            other.getWeight())) return false;
    if (position_ != other.position_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getNameCount() > 0) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameList().hashCode();
    }
    hash = (37 * hash) + DATEOFBIRTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDateOfBirth());
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHeight()));
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeight()));
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + position_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sts.rpclib.PlayerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sts.rpclib.PlayerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sts.rpclib.PlayerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sts.rpclib.PlayerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sts.rpclib.PlayerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.sts.rpclib.PlayerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sts.rpclib.PlayerMessage)
      com.sts.rpclib.PlayerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sts.rpclib.PlayerProfile.internal_static_com_sts_rpclib_PlayerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sts.rpclib.PlayerProfile.internal_static_com_sts_rpclib_PlayerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sts.rpclib.PlayerMessage.class, com.sts.rpclib.PlayerMessage.Builder.class);
    }

    // Construct using com.sts.rpclib.PlayerMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      if (nameBuilder_ == null) {
        name_ = java.util.Collections.emptyList();
      } else {
        name_ = null;
        nameBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      dateOfBirth_ = 0L;
      height_ = 0D;
      weight_ = 0D;
      position_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sts.rpclib.PlayerProfile.internal_static_com_sts_rpclib_PlayerMessage_descriptor;
    }

    @java.lang.Override
    public com.sts.rpclib.PlayerMessage getDefaultInstanceForType() {
      return com.sts.rpclib.PlayerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.sts.rpclib.PlayerMessage build() {
      com.sts.rpclib.PlayerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sts.rpclib.PlayerMessage buildPartial() {
      com.sts.rpclib.PlayerMessage result = new com.sts.rpclib.PlayerMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.sts.rpclib.PlayerMessage result) {
      if (nameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          name_ = java.util.Collections.unmodifiableList(name_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
    }

    private void buildPartial0(com.sts.rpclib.PlayerMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.dateOfBirth_ = dateOfBirth_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.height_ = height_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.weight_ = weight_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.position_ = position_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sts.rpclib.PlayerMessage) {
        return mergeFrom((com.sts.rpclib.PlayerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sts.rpclib.PlayerMessage other) {
      if (other == com.sts.rpclib.PlayerMessage.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (nameBuilder_ == null) {
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
      } else {
        if (!other.name_.isEmpty()) {
          if (nameBuilder_.isEmpty()) {
            nameBuilder_.dispose();
            nameBuilder_ = null;
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000002);
            nameBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNameFieldBuilder() : null;
          } else {
            nameBuilder_.addAllMessages(other.name_);
          }
        }
      }
      if (other.getDateOfBirth() != 0L) {
        setDateOfBirth(other.getDateOfBirth());
      }
      if (other.getHeight() != 0D) {
        setHeight(other.getHeight());
      }
      if (other.getWeight() != 0D) {
        setWeight(other.getWeight());
      }
      if (other.position_ != 0) {
        setPositionValue(other.getPositionValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.sts.rpclib.LocalizedName m =
                  input.readMessage(
                      com.sts.rpclib.LocalizedName.parser(),
                      extensionRegistry);
              if (nameBuilder_ == null) {
                ensureNameIsMutable();
                name_.add(m);
              } else {
                nameBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              dateOfBirth_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 33: {
              height_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              weight_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              position_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.sts.rpclib.LocalizedName> name_ =
      java.util.Collections.emptyList();
    private void ensureNameIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        name_ = new java.util.ArrayList<com.sts.rpclib.LocalizedName>(name_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sts.rpclib.LocalizedName, com.sts.rpclib.LocalizedName.Builder, com.sts.rpclib.LocalizedNameOrBuilder> nameBuilder_;

    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public java.util.List<com.sts.rpclib.LocalizedName> getNameList() {
      if (nameBuilder_ == null) {
        return java.util.Collections.unmodifiableList(name_);
      } else {
        return nameBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public int getNameCount() {
      if (nameBuilder_ == null) {
        return name_.size();
      } else {
        return nameBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public com.sts.rpclib.LocalizedName getName(int index) {
      if (nameBuilder_ == null) {
        return name_.get(index);
      } else {
        return nameBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder setName(
        int index, com.sts.rpclib.LocalizedName value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
      } else {
        nameBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder setName(
        int index, com.sts.rpclib.LocalizedName.Builder builderForValue) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.set(index, builderForValue.build());
        onChanged();
      } else {
        nameBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder addName(com.sts.rpclib.LocalizedName value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
      } else {
        nameBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder addName(
        int index, com.sts.rpclib.LocalizedName value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.add(index, value);
        onChanged();
      } else {
        nameBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder addName(
        com.sts.rpclib.LocalizedName.Builder builderForValue) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.add(builderForValue.build());
        onChanged();
      } else {
        nameBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder addName(
        int index, com.sts.rpclib.LocalizedName.Builder builderForValue) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.add(index, builderForValue.build());
        onChanged();
      } else {
        nameBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder addAllName(
        java.lang.Iterable<? extends com.sts.rpclib.LocalizedName> values) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, name_);
        onChanged();
      } else {
        nameBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        nameBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public Builder removeName(int index) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.remove(index);
        onChanged();
      } else {
        nameBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public com.sts.rpclib.LocalizedName.Builder getNameBuilder(
        int index) {
      return getNameFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public com.sts.rpclib.LocalizedNameOrBuilder getNameOrBuilder(
        int index) {
      if (nameBuilder_ == null) {
        return name_.get(index);  } else {
        return nameBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
         getNameOrBuilderList() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(name_);
      }
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public com.sts.rpclib.LocalizedName.Builder addNameBuilder() {
      return getNameFieldBuilder().addBuilder(
          com.sts.rpclib.LocalizedName.getDefaultInstance());
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public com.sts.rpclib.LocalizedName.Builder addNameBuilder(
        int index) {
      return getNameFieldBuilder().addBuilder(
          index, com.sts.rpclib.LocalizedName.getDefaultInstance());
    }
    /**
     * <code>repeated .com.sts.rpclib.LocalizedName name = 2;</code>
     */
    public java.util.List<com.sts.rpclib.LocalizedName.Builder> 
         getNameBuilderList() {
      return getNameFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sts.rpclib.LocalizedName, com.sts.rpclib.LocalizedName.Builder, com.sts.rpclib.LocalizedNameOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sts.rpclib.LocalizedName, com.sts.rpclib.LocalizedName.Builder, com.sts.rpclib.LocalizedNameOrBuilder>(
                name_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private long dateOfBirth_ ;
    /**
     * <code>int64 dateOfBirth = 3;</code>
     * @return The dateOfBirth.
     */
    @java.lang.Override
    public long getDateOfBirth() {
      return dateOfBirth_;
    }
    /**
     * <code>int64 dateOfBirth = 3;</code>
     * @param value The dateOfBirth to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfBirth(long value) {

      dateOfBirth_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 dateOfBirth = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateOfBirth() {
      bitField0_ = (bitField0_ & ~0x00000004);
      dateOfBirth_ = 0L;
      onChanged();
      return this;
    }

    private double height_ ;
    /**
     * <code>double height = 4;</code>
     * @return The height.
     */
    @java.lang.Override
    public double getHeight() {
      return height_;
    }
    /**
     * <code>double height = 4;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(double value) {

      height_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      height_ = 0D;
      onChanged();
      return this;
    }

    private double weight_ ;
    /**
     * <code>double weight = 5;</code>
     * @return The weight.
     */
    @java.lang.Override
    public double getWeight() {
      return weight_;
    }
    /**
     * <code>double weight = 5;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(double value) {

      weight_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double weight = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      bitField0_ = (bitField0_ & ~0x00000010);
      weight_ = 0D;
      onChanged();
      return this;
    }

    private int position_ = 0;
    /**
     * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
     * @return The enum numeric value on the wire for position.
     */
    @java.lang.Override public int getPositionValue() {
      return position_;
    }
    /**
     * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
     * @param value The enum numeric value on the wire for position to set.
     * @return This builder for chaining.
     */
    public Builder setPositionValue(int value) {
      position_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
     * @return The position.
     */
    @java.lang.Override
    public com.sts.rpclib.ParticipantPosition getPosition() {
      com.sts.rpclib.ParticipantPosition result = com.sts.rpclib.ParticipantPosition.forNumber(position_);
      return result == null ? com.sts.rpclib.ParticipantPosition.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(com.sts.rpclib.ParticipantPosition value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      position_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.sts.rpclib.ParticipantPosition position = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000020);
      position_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sts.rpclib.PlayerMessage)
  }

  // @@protoc_insertion_point(class_scope:com.sts.rpclib.PlayerMessage)
  private static final com.sts.rpclib.PlayerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sts.rpclib.PlayerMessage();
  }

  public static com.sts.rpclib.PlayerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerMessage>
      PARSER = new com.google.protobuf.AbstractParser<PlayerMessage>() {
    @java.lang.Override
    public PlayerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sts.rpclib.PlayerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

