// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rankings.proto

package com.sts.rpclib;

public interface RankingEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.RankingEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string teamId = 1;</code>
   * @return The teamId.
   */
  java.lang.String getTeamId();
  /**
   * <code>string teamId = 1;</code>
   * @return The bytes for teamId.
   */
  com.google.protobuf.ByteString
      getTeamIdBytes();

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 2;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getTeamNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 2;</code>
   */
  com.sts.rpclib.LocalizedName getTeamName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 2;</code>
   */
  int getTeamNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 2;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getTeamNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 2;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getTeamNameOrBuilder(
      int index);

  /**
   * <code>int32 ranking = 3;</code>
   * @return The ranking.
   */
  int getRanking();

  /**
   * <code>int32 previousRanking = 4;</code>
   * @return The previousRanking.
   */
  int getPreviousRanking();

  /**
   * <code>int32 wins = 5;</code>
   * @return The wins.
   */
  int getWins();

  /**
   * <code>int32 losses = 6;</code>
   * @return The losses.
   */
  int getLosses();

  /**
   * <code>int32 points = 7;</code>
   * @return The points.
   */
  int getPoints();
}
