// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.sts.rpclib;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\016com.sts.rpclib\032\016envelope.pr" +
      "oto2\267\001\n\rEventsService\022O\n\014SendEnvelope\022\034." +
      "com.sts.rpclib.EventMessage\032\037.com.sts.rp" +
      "clib.ResponseMessage\"\000\022U\n\rSendHeartbeat\022" +
      " .com.sts.rpclib.HeartbeatMessage\032 .com." +
      "sts.rpclib.HeartbeatMessage\"\000B\rP\001Z\t/gorp" +
      "clibb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sts.rpclib.Envelope.getDescriptor(),
        });
    com.sts.rpclib.Envelope.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
