// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stages.proto

package com.sts.rpclib;

public interface StageParticipantsStatisticsMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.StageParticipantsStatisticsMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sts.rpclib.ParticipantMessage participants = 1;</code>
   */
  java.util.List<com.sts.rpclib.ParticipantMessage> 
      getParticipantsList();
  /**
   * <code>repeated .com.sts.rpclib.ParticipantMessage participants = 1;</code>
   */
  com.sts.rpclib.ParticipantMessage getParticipants(int index);
  /**
   * <code>repeated .com.sts.rpclib.ParticipantMessage participants = 1;</code>
   */
  int getParticipantsCount();
  /**
   * <code>repeated .com.sts.rpclib.ParticipantMessage participants = 1;</code>
   */
  java.util.List<? extends com.sts.rpclib.ParticipantMessageOrBuilder> 
      getParticipantsOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.ParticipantMessage participants = 1;</code>
   */
  com.sts.rpclib.ParticipantMessageOrBuilder getParticipantsOrBuilder(
      int index);

  /**
   * <code>string stageId = 2;</code>
   * @return The stageId.
   */
  java.lang.String getStageId();
  /**
   * <code>string stageId = 2;</code>
   * @return The bytes for stageId.
   */
  com.google.protobuf.ByteString
      getStageIdBytes();

  /**
   * <code>string season = 3;</code>
   * @return The season.
   */
  java.lang.String getSeason();
  /**
   * <code>string season = 3;</code>
   * @return The bytes for season.
   */
  com.google.protobuf.ByteString
      getSeasonBytes();

  /**
   * <code>.com.sts.rpclib.Sport sport = 4;</code>
   * @return The enum numeric value on the wire for sport.
   */
  int getSportValue();
  /**
   * <code>.com.sts.rpclib.Sport sport = 4;</code>
   * @return The sport.
   */
  com.sts.rpclib.Sport getSport();
}
