// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match.proto

package com.sts.rpclib;

public interface AddCommentaryMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.AddCommentaryMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.sts.rpclib.Language language = 1;</code>
   * @return The enum numeric value on the wire for language.
   */
  int getLanguageValue();
  /**
   * <code>.com.sts.rpclib.Language language = 1;</code>
   * @return The language.
   */
  com.sts.rpclib.Language getLanguage();

  /**
   * <code>.com.sts.rpclib.MatchCommentaryEntry commentary = 2;</code>
   * @return Whether the commentary field is set.
   */
  boolean hasCommentary();
  /**
   * <code>.com.sts.rpclib.MatchCommentaryEntry commentary = 2;</code>
   * @return The commentary.
   */
  com.sts.rpclib.MatchCommentaryEntry getCommentary();
  /**
   * <code>.com.sts.rpclib.MatchCommentaryEntry commentary = 2;</code>
   */
  com.sts.rpclib.MatchCommentaryEntryOrBuilder getCommentaryOrBuilder();
}
