// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: league_tables.proto

package com.sts.rpclib;

public interface LeagueTableEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.LeagueTableEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ranking = 1;</code>
   * @return The ranking.
   */
  int getRanking();

  /**
   * <code>string team_id = 2;</code>
   * @return The teamId.
   */
  java.lang.String getTeamId();
  /**
   * <code>string team_id = 2;</code>
   * @return The bytes for teamId.
   */
  com.google.protobuf.ByteString
      getTeamIdBytes();

  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 3;</code>
   */
  java.util.List<com.sts.rpclib.LocalizedName> 
      getTeamNameList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 3;</code>
   */
  com.sts.rpclib.LocalizedName getTeamName(int index);
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 3;</code>
   */
  int getTeamNameCount();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 3;</code>
   */
  java.util.List<? extends com.sts.rpclib.LocalizedNameOrBuilder> 
      getTeamNameOrBuilderList();
  /**
   * <code>repeated .com.sts.rpclib.LocalizedName team_name = 3;</code>
   */
  com.sts.rpclib.LocalizedNameOrBuilder getTeamNameOrBuilder(
      int index);

  /**
   * <code>string played = 4;</code>
   * @return The played.
   */
  java.lang.String getPlayed();
  /**
   * <code>string played = 4;</code>
   * @return The bytes for played.
   */
  com.google.protobuf.ByteString
      getPlayedBytes();

  /**
   * <code>string wins = 5;</code>
   * @return The wins.
   */
  java.lang.String getWins();
  /**
   * <code>string wins = 5;</code>
   * @return The bytes for wins.
   */
  com.google.protobuf.ByteString
      getWinsBytes();

  /**
   * <code>string draws = 6;</code>
   * @return The draws.
   */
  java.lang.String getDraws();
  /**
   * <code>string draws = 6;</code>
   * @return The bytes for draws.
   */
  com.google.protobuf.ByteString
      getDrawsBytes();

  /**
   * <code>string loss = 7;</code>
   * @return The loss.
   */
  java.lang.String getLoss();
  /**
   * <code>string loss = 7;</code>
   * @return The bytes for loss.
   */
  com.google.protobuf.ByteString
      getLossBytes();

  /**
   * <code>string goal_for = 8;</code>
   * @return The goalFor.
   */
  java.lang.String getGoalFor();
  /**
   * <code>string goal_for = 8;</code>
   * @return The bytes for goalFor.
   */
  com.google.protobuf.ByteString
      getGoalForBytes();

  /**
   * <code>string goal_against = 9;</code>
   * @return The goalAgainst.
   */
  java.lang.String getGoalAgainst();
  /**
   * <code>string goal_against = 9;</code>
   * @return The bytes for goalAgainst.
   */
  com.google.protobuf.ByteString
      getGoalAgainstBytes();

  /**
   * <code>string goal_difference = 10;</code>
   * @return The goalDifference.
   */
  java.lang.String getGoalDifference();
  /**
   * <code>string goal_difference = 10;</code>
   * @return The bytes for goalDifference.
   */
  com.google.protobuf.ByteString
      getGoalDifferenceBytes();

  /**
   * <code>string points = 11;</code>
   * @return The points.
   */
  java.lang.String getPoints();
  /**
   * <code>string points = 11;</code>
   * @return The bytes for points.
   */
  com.google.protobuf.ByteString
      getPointsBytes();

  /**
   * <code>string percentage = 12;</code>
   * @return The percentage.
   */
  java.lang.String getPercentage();
  /**
   * <code>string percentage = 12;</code>
   * @return The bytes for percentage.
   */
  com.google.protobuf.ByteString
      getPercentageBytes();

  /**
   * <code>.com.sts.rpclib.LeagueTableEntry.LeagueTableKind league_table_kind = 13;</code>
   * @return The enum numeric value on the wire for leagueTableKind.
   */
  int getLeagueTableKindValue();
  /**
   * <code>.com.sts.rpclib.LeagueTableEntry.LeagueTableKind league_table_kind = 13;</code>
   * @return The leagueTableKind.
   */
  com.sts.rpclib.LeagueTableEntry.LeagueTableKind getLeagueTableKind();

  /**
   * <code>repeated int32 stage_phases = 14;</code>
   * @return A list containing the stagePhases.
   */
  java.util.List<java.lang.Integer> getStagePhasesList();
  /**
   * <code>repeated int32 stage_phases = 14;</code>
   * @return The count of stagePhases.
   */
  int getStagePhasesCount();
  /**
   * <code>repeated int32 stage_phases = 14;</code>
   * @param index The index of the element to return.
   * @return The stagePhases at the given index.
   */
  int getStagePhases(int index);

  /**
   * <code>string points_deduction = 15;</code>
   * @return The pointsDeduction.
   */
  java.lang.String getPointsDeduction();
  /**
   * <code>string points_deduction = 15;</code>
   * @return The bytes for pointsDeduction.
   */
  com.google.protobuf.ByteString
      getPointsDeductionBytes();
}
