// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match.proto

package com.sts.rpclib;

public interface MatchStatsMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sts.rpclib.MatchStatsMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 teamPosition = 1;</code>
   * @return The teamPosition.
   */
  int getTeamPosition();

  /**
   * <code>map&lt;int32, int32&gt; stats = 15;</code>
   */
  int getStatsCount();
  /**
   * <code>map&lt;int32, int32&gt; stats = 15;</code>
   */
  boolean containsStats(
      int key);
  /**
   * Use {@link #getStatsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getStats();
  /**
   * <code>map&lt;int32, int32&gt; stats = 15;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getStatsMap();
  /**
   * <code>map&lt;int32, int32&gt; stats = 15;</code>
   */

  int getStatsOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; stats = 15;</code>
   */

  int getStatsOrThrow(
      int key);
}
